// src/app/demo/page1/page1.component.ts
import { Component, OnInit } from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { HttpClient } from '@angular/common/http';

import { NzMessageService } from 'ng-zorro-antd';
import { utils } from 'xlsx';
import { Workbook, Table } from './workbook.model';
import { ExcelConfig } from './excel-config.model';
import * as moment from 'moment-timezone';

@Component({
  selector: 'app-page1',
  templateUrl: './page1.component.html',
  styleUrls: ['./page1.component.less']
})
export class Page1Component implements OnInit {
  accepts = [
    'application/vnd.ms-excel',
    'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
  ];
  rABS = true; // true:readAsBinaryString; false:readAsArrayBuffer;
  tableHeader = [];
  tableData = [];
  validateForm: FormGroup;
  isShow = true;
  config: ExcelConfig;

  constructor(
    private msg: NzMessageService,
    private fb: FormBuilder,
    private http: HttpClient
  ) {}

  ngOnInit() {
    moment.locale('zh-cn');
    this.validateForm = this.fb.group({
      myID: [null, [Validators.required]],
      myEndPoint: [null]
    });
    this.http
      .get<ExcelConfig>('/assets/data/excel-config.json')
      .toPromise()
      .then(resp => {
        this.validateForm.setValue({
          myID: resp.myID,
          myEndPoint: resp.myEndPoint
        });
        this.config = resp;
      });
  }

  submitForm() {
    this.isShow = !this.isShow;
  }

  /**
   * @description 上传文件之前，对上传的文件进行校验
   */
  beforeUpload = (file: File) => {
    const isAccept = this.accepts.includes(file.type);
    const isLimit = file.size / 1024 / 1024 < 10;
    if (!isAccept) {
      this.msg.error('只能上传xls/xlsx文件');
      return false;
    }
    if (!isLimit) {
      this.msg.error('上传的文件大小不能超过10MB');
      return false;
    }
    if (isAccept && isLimit) {
      this.readFile(file);
    }
    return false;
  };

  /**
   * @description 读取Excel文件
   * @param file Excel文件
   */
  readFile(file: File) {
    this.config.fileName = file.name;
    const reader = new FileReader();
    reader.onload = () => {
      const wb = Workbook.readWorkbook(reader, this.rABS);
      if (wb.SheetNames.length < 2) {
        this.msg.error('Excel中Sheet页的数量小于2，数据不完整无法解析。');
        return;
      }
      const empSheetName = wb.SheetNames[this.config.empPageIndex]; // 员工加班记录明细页索引
      const empSheet = wb.Sheets[empSheetName];
      this.config.mySheetName = wb.SheetNames[this.config.myPageIndex]; // 个人加班记录明细页索引
      const mySheet = wb.Sheets[this.config.mySheetName];
      this.tableHeader = Workbook.getHeaderRow(mySheet); // 表头行
      const empData = utils
        .sheet_to_json(empSheet, { header: 1, blankrows: false })
        .filter(x => x[this.config.idIndex] === this.config.myID)
        .map(x => {
          this.config.myName = x[this.config.nameIndex];
          x[this.config.overtimeIndex] = this.formatOverTime(
            x[this.config.overtimeIndex]
          );
          return x;
        });
      empData.forEach(x => {
        this.tableData.push([
          x[this.config.deptIndex],
          x[this.config.approvalIndex],
          x[this.config.nameIndex] + '-餐费',
          ...this.config.mealFee,
          x[this.config.overtimeIndex],
          x[this.config.deadlineIndex]
        ]);
        if (this.isAfterTime(x[this.config.deadlineIndex])) {
          this.tableData.push([
            x[this.config.deptIndex],
            x[this.config.approvalIndex],
            x[this.config.nameIndex] + '-交通',
            ...this.config.trafficFee1,
            x[this.config.overtimeIndex],
            x[this.config.deadlineIndex],
            ...this.config.trafficFee2,
            this.config.myEndPoint
          ]);
        }
      });
    };
    Workbook.fileReadAs(this.rABS, reader, file);
  }

  /**
   * @description 导出Excel文件
   */
  exportExcel() {
    if (this.tableData.length === 0) {
      this.msg.error('当前表格没有可用数据');
      return;
    }
    const wb = new Workbook();
    const ws = utils.json_to_sheet([this.tableHeader, ...this.tableData], {
      skipHeader: true
    });
    wb.SheetNames.push(this.config.mySheetName);
    wb.Sheets[this.config.mySheetName] = ws;
    wb.writeWorkbook(this.config.myName + '-' + this.config.fileName);
  }

  isAfterTime(time) {
    const deadline = moment(time, this.config.timeFormat).tz(
      this.config.timezone
    ); // 加班截止时间
    const startTime = moment(this.config.taxiTime, this.config.timeFormat).tz(
      this.config.timezone
    ); // 规定打车开始时间
    return deadline.isSameOrAfter(startTime);
  }

  formatOverTime(time) {
    return moment(time, this.config.dateParse).format(this.config.dateFormat);
  }
}

<ng-template [ngIf]="this.isShowForm">
  <form nz-form [formGroup]="validateForm" (ngSubmit)="submitForm()" nzLayout="inline">
    <nz-form-item>
      <nz-form-control>
        <input nz-input formControlName="myID" placeholder="请输入员工编号" [nzAutocomplete]="idAuto" style="width: 200px">
        <nz-autocomplete #idAuto [nzDataSource]="config?.userIds || []" [nzBackfill]="true"></nz-autocomplete>
        <nz-form-explain *ngIf="validateForm.get('myID').dirty && validateForm.get('myID').errors">请输入员工编号！</nz-form-explain>
      </nz-form-control>
    </nz-form-item>
    <nz-form-item>
      <nz-form-control>
        <input nz-input formControlName="myEndPoint" placeholder="请输入下车地点" [nzAutocomplete]="pointAuto" style="width: 200px">
        <nz-autocomplete #pointAuto [nzDataSource]="config?.endPoints || []" [nzBackfill]="true"></nz-autocomplete>
      </nz-form-control>
    </nz-form-item>
    <nz-form-item>
      <nz-form-control>
        <button nz-button nzType="primary" [disabled]="!validateForm.valid">下一步</button>
      </nz-form-control>
    </nz-form-item>
  </form>
</ng-template>
<ng-template [ngIf]="!this.isShowForm">
  <nz-upload nzType="drag" [nzAccept]="accepts.toString()" [nzBeforeUpload]="beforeUpload" [ngStyle]="{'display':this.isShowUpload?'block':'none'}">
    <p class="ant-upload-drag-icon">
      <i class="anticon anticon-inbox"></i>
    </p>
    <p class="ant-upload-text">点击或拖动文件到这个区域上传</p>
    <p class="ant-upload-hint">将文件拖到此处或点击上传，只能上传xls/xlsx文件。</p>
  </nz-upload>
  <div class="table-operations">
    <button nz-button (click)="goBack()">上一步</button>&nbsp;
    <button nz-button (click)="this.isShowUpload = !this.isShowUpload">折叠|展开</button>&nbsp;
    <button nz-button (click)="batchDelete()" nzType="danger" [disabled]="disabledButton">批量删除</button>&nbsp;
    <ng-template [ngIf]="this.tableData.length !== 0">
      <button nz-button (click)="exportExcel()">导出Excel文件</button>
    </ng-template>
    员工编号：{{config.myID}}， 下车地点：{{config.myEndPoint}}
  </div>
  <ng-template [ngIf]="this.tableData.length !== 0">
    <nz-table #nzTable [nzData]="this.tableData" [nzFrontPagination]="false" [nzShowPagination]="false" nzSize="small" [nzScroll]="{x:'4050px',y:'480px'}"
      [nzBordered]="true">
      <thead>
        <tr>
          <th nzShowCheckbox [(nzChecked)]="allChecked" [nzIndeterminate]="indeterminate" (nzCheckedChange)="checkAll($event)"></th>
          <th *ngFor="let item of this.tableHeader" nzWidth="150px">
            <span>{{item}}</span>
          </th>
        </tr>
      </thead>
      <tbody>
        <tr *ngFor="let data of nzTable.data;even as isEven" [ngStyle]="{'background':isEven?'#fdf5e6':'auto'}">
          <td nzShowCheckbox [(nzChecked)]="checkboxCache[data[data.length-1]]" (nzCheckedChange)="refreshStatus()"></td>
          <ng-container *ngFor="let item of data;index as col;last as isLast;count as total">
            <td *ngIf="!isLast">
              <div class="editable-cell">
                <div class="editable-cell-text-wrapper">
                  <ng-container [ngSwitch]="col">
                    <ng-template [ngSwitchCase]="config.moneyIndex">
                      <ng-template [ngIf]="!editMoneyCache[data[total-1]].edit && editMoneyCache[data[total-1]].isTraffic">
                        {{item}}
                        <i class="anticon anticon-edit editable-cell-icon" (click)="startEdit(data[total-1],col)"></i>
                      </ng-template>
                      <ng-template [ngIf]="editMoneyCache[data[total-1]].edit && editMoneyCache[data[total-1]].isTraffic">
                        <nz-input-number [(ngModel)]="editMoneyCache[data[total-1]].value" [nzStep]="1" [nzMin]="0" nzPlaceHolder="交通费"></nz-input-number>
                        <i class="anticon anticon-check editable-cell-icon-check" (click)="finishEdit(data[total-1],col)"></i>
                      </ng-template>
                      <ng-template [ngIf]="!editMoneyCache[data[total-1]].isTraffic">{{item}}</ng-template>
                    </ng-template>
                    <ng-template [ngSwitchCase]="config.startTimeIndex">
                      <ng-template [ngIf]="!editStartTimeCache[data[total-1]].edit && editStartTimeCache[data[total-1]].isTraffic">
                        {{item}}
                        <i class="anticon anticon-edit editable-cell-icon" (click)="startEdit(data[total-1],col)"></i>
                      </ng-template>
                      <ng-template [ngIf]="editStartTimeCache[data[total-1]].edit && editStartTimeCache[data[total-1]].isTraffic">
                        <nz-time-picker [(ngModel)]="editStartTimeCache[data[total-1]].value" [nzFormat]="config.shortTimeFormat" [nzDisabledHours]="disabledHours"
                          [nzHideDisabledOptions]="true" nzClearText="清除上车时间"></nz-time-picker>
                        <i class="anticon anticon-check editable-cell-icon-check" (click)="finishEdit(data[total-1],col)"></i>
                      </ng-template>
                    </ng-template>
                    <ng-template [ngSwitchCase]="config.endTimeIndex">
                      <ng-template [ngIf]="!editEndTimeCache[data[total-1]].edit && editEndTimeCache[data[total-1]].isTraffic">
                        {{item}}
                        <i class="anticon anticon-edit editable-cell-icon" (click)="startEdit(data[total-1],col)"></i>
                      </ng-template>
                      <ng-template [ngIf]="editEndTimeCache[data[total-1]].edit && editEndTimeCache[data[total-1]].isTraffic">
                        <nz-time-picker [(ngModel)]="editEndTimeCache[data[total-1]].value" [nzFormat]="config.shortTimeFormat" [nzDisabledHours]="disabledHours"
                          [nzHideDisabledOptions]="true" nzClearText="清除下车时间"></nz-time-picker>
                        <i class="anticon anticon-check editable-cell-icon-check" (click)="finishEdit(data[total-1],col)"></i>
                      </ng-template>
                    </ng-template>
                    <ng-template ngSwitchDefault>{{item}}</ng-template>
                  </ng-container>
                </div>
              </div>
            </td>
          </ng-container>
        </tr>
      </tbody>
    </nz-table>
  </ng-template>
</ng-template>

// src/views/nav2/page1.vue
<template>
  <el-row>
    <template v-if="isShow">
      <el-col :span="6">
        员工号：（必填）
        <el-input v-model.trim="params.myID" placeholder="请输入员工号" clearable></el-input>
      </el-col>
      <el-col :span="2">&nbsp;</el-col>
      <el-col :span="6">
        下车地点：（选填）
        <el-input v-model.trim="params.myEndPoint" placeholder="请输入下车地点" clearable></el-input>
      </el-col>
      <el-col :span="2">&nbsp;</el-col>
      <el-col :span="24">&nbsp;</el-col>
      <el-col :span="24">
        <el-button type="primary" @click="toNext" :disabled="!params.myID">下一步</el-button>
      </el-col>
    </template>
    <template v-else>
      <el-col :span="10">
        <el-upload drag :action="action" :accept="accepts.toString()" :before-upload="beforeUpload">
          <i class="el-icon-upload"></i>
          <div class="el-upload__text">将文件拖到此处，或
            <em>点击上传</em><br>只能上传xls/xlsx文件</div>
        </el-upload>
      </el-col>
      <el-col :span="14">
        <el-button type="primary" @click="toBack">上一步</el-button>
        <el-button type="primary" @click="exportExcel" :disabled="tableData.length===0">导出Excel文件</el-button>
      </el-col>
      <el-col :span="24">
        <el-table :data="tableData" border highlight-current-row stripe size="mini">
          <el-table-column v-for="(item,index) of tableHeader" :key="item" :label="item" :prop="`${index}`"></el-table-column>
        </el-table>
      </el-col>
    </template>
  </el-row>
</template>
<script>
import XLSX from 'xlsx';
import Workbook from './workbook';
import moment from 'moment-timezone';
moment.locale('zh-cn');
export default {
  name: 'my-page1',
  data: () => ({
    action: '',
    accepts: [
      'application/vnd.ms-excel',
      'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
    ],
    tableData: [],
    tableHeader: [],
    isShow: true,
    rABS: true, //true:readAsBinaryString; false:readAsArrayBuffer;
    params: {
      // myID: '8143969', // 员工号
      // myEndPoint: '家（西城区阜成门内）', //下车地点
      // myName: '', // 员工姓名
      // idIndex: 1, // 员工号索引
      // nameIndex: 2, // 员工姓名索引
      // deptIndex: 3, // 部门索引
      // approvalIndex: 6, // 审批单号索引
      // overtimeIndex: 8, // 加班日期索引
      // deadlineIndex: 10, // 加班截止时间索引
      // empPageIndex: 0, // 员工加班记录明细页索引
      // myPageIndex: 1, // 个人加班记录明细页索引
      // dateParse: 'MM/DD/YY', //解析字符串日期样式
      // dateFormat: 'YYYY/MM/DD', //格式化日期样式
      // timeFormat: 'HH:mm:ss', //格式化时间样式
      // timezone: 'Asia/Shanghai', //中国时区
      // taxiTime: '21:00:00', //规定打车开始时间
      // mySheetName: '',
      // fileName: ''
    }
  }),
  methods: {
    toNext() {
      if (!this.params.myID) {
        this.$message.error('请输入员工号');
        return;
      }
      this.isShow = !this.isShow;
    },
    toBack() {
      this.isShow = !this.isShow;
      this.tableData = [];
      this.tableHeader = [];
    },
    exportExcel() {
      if (this.tableData.length === 0) {
        this.$message.error('当前表格没有可用数据');
        return;
      }
      const wb = new Workbook();
      const ws = XLSX.utils.json_to_sheet(
        [this.tableHeader, ...this.tableData],
        { skipHeader: true }
      );
      wb.SheetNames.push(this.params.mySheetName);
      wb.Sheets[this.params.mySheetName] = ws;
      wb.writeWorkbook(this.params.myName + '-' + this.params.fileName);
    },
    beforeUpload(file) {
      this.params.fileName = file.name;
      const isAccept = this.accepts.includes(file.type);
      const isLimit = file.size / 1024 / 1024 < 10;
      if (!isAccept) {
        this.$message.error('只能上传xls/xlsx文件');
        return false;
      }
      if (!isLimit) {
        this.$message.error('上传的文件大小不能超过10MB');
        return false;
      }
      if (isAccept && isLimit) {
        const reader = new FileReader();
        reader.onload = () => {
          const wb = Workbook.readWorkbook(reader, this.rABS);
          if (wb.SheetNames.length < 2) {
            this.$message.error(
              'Excel中Sheet页的数量小于2，数据不完整无法解析。'
            );
            return;
          }
          const empSheetName = wb.SheetNames[this.params.empPageIndex]; // 员工加班记录明细页索引
          const empSheet = wb.Sheets[empSheetName];
          this.params.mySheetName = wb.SheetNames[this.params.myPageIndex]; // 个人加班记录明细页索引
          const mySheet = wb.Sheets[this.params.mySheetName];
          this.tableHeader = Workbook.getHeaderRow(mySheet); // 表头行
          const empData = XLSX.utils
            .sheet_to_json(empSheet, { header: 1, blankrows: false })
            .filter(x => x[this.params.idIndex] === this.params.myID)
            .map(x => {
              this.params.myName = x[this.params.nameIndex];
              x[this.params.overtimeIndex] = this.formatOverTime(
                x[this.params.overtimeIndex]
              );
              return x;
            });
          empData.forEach(x => {
            this.tableData.push([
              x[this.params.deptIndex],
              x[this.params.approvalIndex],
              x[this.params.nameIndex] + '-餐费',
              ...this.params.mealFee,
              x[this.params.overtimeIndex],
              x[this.params.deadlineIndex]
            ]);
            if (this.isAfterTime(x[this.params.deadlineIndex])) {
              this.tableData.push([
                x[this.params.deptIndex],
                x[this.params.approvalIndex],
                x[this.params.nameIndex] + '-交通',
                ...this.params.trafficFee1,
                x[this.params.overtimeIndex],
                x[this.params.deadlineIndex],
                ...this.params.trafficFee2,
                this.params.myEndPoint
              ]);
            }
          });
        };
        Workbook.fileReadAs(this.rABS, reader, file);
      }
      return false;
    },
    formatOverTime(time) {
      return moment(time, this.params.dateParse).format(this.params.dateFormat);
    },
    isAfterTime(time) {
      const deadline = moment(time, this.params.timeFormat).tz(
        this.params.timezone
      ); //加班截止时间
      const startTime = moment(this.params.taxiTime, this.params.timeFormat).tz(
        this.params.timezone
      ); //规定打车开始时间
      return deadline.isSameOrAfter(startTime);
    }
  },
  mounted() {
    fetch('/static/data/excel-config.json')
      .then(res => res.json())
      .then(data => {
        this.params = data;
      });
  }
};
</script>
